spring:
  application:
    name: art
  datasource:
    url: jdbc:postgresql://localhost:5432/art
    username: art
    password: fsdArt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8090