spring:
  application:
    name: art
  datasource:
    url: jdbc:postgresql://localhost:5555/jay
    username: jay
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8090

cloudinary:
  name: 88888888888888888888
  api:
    key: 888888888888888888888888
    secret-key: 888888888888888888888888888
